=== gabrimdez/3-Lenguaje-de-marcas/xml/ej5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="programacion" type="tipoProgramacion" />

    <xs:complexType name="tipoProgramacion">
        <xs:sequence>
            <xs:element name="lenguaje" type="tipoLenguaje" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="tipoLenguaje">
        <xs:sequence>
            <xs:element ref="nombre" />
            <xs:element ref="creador" />
            <xs:element ref="anioCreacion" />
            <xs:element ref="descripcion" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="nombre">
        <xs:simpleType>
            <xs:restriction base="xs:string">

            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="creador">
        <xs:simpleType>
            <xs:restriction base="xs:string">

            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="anioCreacion">
        <xs:simpleType>
            <xs:restriction base="xs:integer">

            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="descripcion">
        <xs:simpleType>
            <xs:restriction base="xs:string">

            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== gabrimdez/3-Lenguaje-de-marcas/xml/ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<programacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej5.xsd">


    <lenguaje>
        <nombre>Python</nombre>
        <creador>Guido van Rossum</creador>
        <anioCreacion>1991</anioCreacion>
        <descripcion>Python is a high-level, interpreted, and general-purpose programming language
            that emphasizes readability with its notable use of significant whitespace.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>Java</nombre>
        <creador>James Gosling</creador>
        <anioCreacion>1995</anioCreacion>
        <descripcion>Java is a class-based, object-oriented programming language that is designed to
            have as few implementation dependencies as possible.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>C++</nombre>
        <creador>Bjarne Stroustrup</creador>
        <anioCreacion>1985</anioCreacion>
        <descripcion>C++ is a general-purpose programming language created as an extension of the C
            programming language, or «C with Classes».</descripcion>
    </lenguaje>


</programacion>
