=== gabrimdez/3-Lenguaje-de-marcas/xml/Ejemplo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receta" type="tipoConjunto" />

    <xs:complexType name="tipoConjunto">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string" />
            <xs:element name="ingredientes" maxOccurs="unbounded" type="xs:string" />
            <xs:element name="procedimiento" maxOccurs="unbounded" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gabrimdez/3-Lenguaje-de-marcas/xml/Ejemplo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo2.xsd">

    <titulo>Pollo al ajillo</titulo>
    <ingredientes>Pechugas de Pollo</ingredientes>
    <ingredientes>Ajos</ingredientes>
    <ingredientes>Pimienta</ingredientes>
    <ingredientes>Sal</ingredientes>
    <procedimiento>Sellamos el pollo</procedimiento>
    <procedimiento>Sofries el ajo</procedimiento>
    <procedimiento>Condimentamos con sal y pimienta</procedimiento>
    <procedimiento>AÃ±adimos el pollo</procedimiento>


</receta>
