=== gabrimdez/3-Lenguaje-de-marcas/xml/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definición de elementos globales -->
    <xs:element name="nombre" type="xs:string" />
    <xs:element name="creador" type="xs:string" />
    <xs:element name="anioDeCreacion" type="xs:int" />
    <xs:element name="descripcion" type="xs:string" />

    <!-- Definición del elemento Lenguajes -->
    <xs:element name="lenguajes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lenguaje" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nombre" />
                            <xs:element ref="creador" />
                            <xs:element ref="anioDeCreacion" />
                            <xs:element ref="descripcion" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== gabrimdez/3-Lenguaje-de-marcas/xml/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<lenguajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio5.xsd">
    <lenguaje>
        <nombre>Python</nombre>
        <creador>Guido van Rossum</creador>
        <anioDeCreacion>1991</anioDeCreacion>
        <descripcion>Python is a high-level, interpreted, and general-purpose programming language that emphasizes readability with its notable use of significant whitespace.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>Java</nombre>
        <creador>James Gosling</creador>
        <anioDeCreacion>1995</anioDeCreacion>
        <descripcion>Java is a class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>C++</nombre>
        <creador>Bjarne Stroustrup</creador>
        <anioDeCreacion>1985</anioDeCreacion>
        <descripcion>C++ is a general-purpose programming language created as an extension of the C programming language, or "C with Classes".</descripcion>
    </lenguaje>
</lenguajes>
